name: CI/CD Pipeline

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: hello-nginx-2
  REGISTRY: ghcr.io/${{ github.repository_owner }}
  TAG: ${{ github.sha }}

jobs:
  check:
    name: Lint + Secrets Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run gitleaks (secret scan)
        uses: gitleaks/gitleaks-action@v2

      - name: Run Hadolint (Dockerfile linter)
        uses: hadolint/hadolint-action@v2.0.0

  build-and-deploy:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          format: table
          severity: CRITICAL,HIGH

      - name: Update GitOps repo with new image tag
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone https://${GITOPS_PAT}@github.com/cristalcorp/minikube.git
          cd minikube
          sed -i "s/tag: .*/tag: ${TAG}/" apps/hello-nginx-2/dev/values.yaml
          git add apps/hello-nginx-2/dev/values.yaml
          git commit -m "Update hello-nginx-2 image tag to ${TAG}"
          git push
        env:
          GITOPS_PAT: ${{ secrets.GITOPS_PAT }}
          TAG: ${{ env.TAG }}
        if: github.ref == 'refs/heads/main'

